name: digitalocean_deploy

on:
  push:
    branches: [main]
    
jobs:
  Build:
    runs-on: self-hosted
    
    steps:
    - name: Run build
      run: docker-compose up -d
      # - uses: actions/checkout@main
      # - name: Create .env
      #   run: echo 'PORT=${{secrets.PORT }}' > .env
        
     
